### ISSUE TITLE
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)

### ISSUE THREAD

**Issue by PrzemekCh** [jacoco/eclemma#103]
Hi 
I'm using latest eclemma with jmockit in eclipse sts 3.6.4
.
Trying to use coverage as I'm getting java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields) error.

I've reported this to the JMockit team https://github.com/jmockit/jmockit1/issues/187 but they said its a jococo issue.

The same here:
http://stackoverflow.com/questions/27316808/using-jmockit-with-eclemma

The interesting thing is that while running jococo via maven everything works fine and the report is generated

I'm using :
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.7.5.201505241946</version>

Could You update the eclipse plugin to use the latest jococo engine?

**Comment by kdesineedi** [comment]
Hi,

I am facing the same problem.Can anyone please let me know what version of EclEmma plugin I need to use in Eclipse Luna to resolve this issue.Looks like jacoco 0.7.5 addresses this issue.

https://github.com/jacoco/jacoco/commit/bc47c020906fde9ce162597cf499fb66e73920fb

Java version being used: 1.8

**Comment by marchof** [comment]
For a version of EclEmma with the latest JaCoCo release included please try this trunk build update site:

http://download.eclipselab.org/eclemma/trunk/update

**Comment by kdesineedi** [comment]
Thanks!This works like a charm

**Comment by marchof** [comment]
Ok, great. There will be a official EclEmma release soon!
