### ISSUE TITLE
Add simple Java projects to the Eclipse coverage launch config

### ISSUE THREAD

**Issue by iloveeclipse** [jacoco/eclemma#104]
AS IS:
If one configures coverage launch of an Eclipse application, one has under "Coverage" tab an "Analysis scope" list with Eclipse projects to select. This list seems to allow selection of Eclipse plugins only. 

We have plugin which uses a plain Java library as part of its classpath, and this library exists also as a simple Java project in the workspace. Unfortunately the coverage of that library cannot be measured during Eclipse coverage launch, probably because Eclemma seem not to find the sources probably because the Java project is not selected in the  "Analysis scope" list.

TO BE:
It would be nice if one could measure of all related source code, including plain Java projects while running Eclipse coverage with Eclemma.

**Comment by marchof** [comment]
@iloveeclipse It is correct that EclEmma only allows selection of package fragment roots of plugin projects. But the library within your plug-in should be selectable on the "Analysis Scope" tab.

Can you please provide your MANIFEST.MF, build.properties and .classpath files?

**Comment by iloveeclipse** [comment]
> But the library within your plug-in should be selectable on the "Analysis Scope" tab.

Yep, and it was *not* selected. Question: is this expected? Shouldn't everything under selected plugin was selected automatically?

**Comment by marchof** [comment]
You can control the default scope in the EclEmma preferences with "Source folders only" option, please see: http://www.eclemma.org/userdoc/preferences.html

**Comment by iloveeclipse** [comment]
A-ha! Never seen that page (obviously defaults were good enough so far :-) ). I see it works, so I wil close the ticket.
 Sorry for noise & thanks for the nice tool.

**Comment by marchof** [comment]
@iloveeclipse No problem!
