### ISSUE TITLE
Code Coverate session gets suspended

### ISSUE THREAD

**Issue by partho-maple** [jacoco/eclemma#105]
I am running a code coverage session for a Java SE project. But while running the coverage session, it gets suspended on different test methods. It doesn't even show any failure tress or any information.

How can i resume test coverage from that point or just ignore/skip(Not using @Ignore annotation. Because it gets stuck of different methods on different time) the methods while the session is in progress ?

Any help will be highly appreciated.

My system details:  Mac OS 10.10.3 ; Eclipse  Luna(4.4.2), and latest EclEmma installed from eclipse marketplace as of now.

![screenshot_18](https://cloud.githubusercontent.com/assets/1577598/9027719/48d1def0-3982-11e5-9ad1-b75c6cd8c0cf.jpg)

**Comment by marchof** [comment]
Do your tests run properly without code coverage (run or debug mode)?

**Comment by partho-maple** [comment]
@marchof :   Yes, each and every test case runs perfectly when i run them separately.

**Comment by marchof** [comment]
@partho-maple This was not my question ;-) Do *all* your test cases run through properly in a row  when executing them in run or debug mode? Or do they also get stuck at different methods?

**Comment by marchof** [comment]
@partho-maple Any updates on this? Can you answer my last question?

**Comment by marchof** [comment]
Closed due to missing feedback.
