### ISSUE TITLE
"Error while creating report" should also include the reason

### ISSUE THREAD

**Issue by ben-spiller** [jacoco/eclemma#107]
If an error occurs creating the report, the only message that is logged by default is "Error while creating report" which of course provides the user with no idea where to look or what to do. The user is left scratching their head for a while, and only by ant into -verbose mode can you get the information you need to understand and fix it. 

It would be very helpful - and trivially easy - to append the message from the exception to that message so the user immediately knows what happened.

**Comment by marchof** [comment]
The issue of missing error messages has been resolved with this issue  #106. Please re-test latest trunk build: http://download.eclipselab.org/eclemma/trunk/update
