### ISSUE TITLE
Report tool should help users to work around "Can't add different class with same name" fatal error

### ISSUE THREAD

**Issue by ben-spiller** [jacoco/eclemma#108]
It's understandable (and explained clearly in the FAQ, thanks) why the "Can't add different class with same name" IllegalStateException is sometimes thrown. 

However despite this it's very difficult at present for a user to cope with it (and I've seen more than one user mention this has caused them pain on the forums), not least because it's very hard to even track down where the conflicting occurrences of the class have come from. 

Two things that would help enormously are:
- if the error message could mention both of the jars/directories that contain the problematic class, as it's very difficult and timeconsuming to find where the conflict could be otherwise
- if there was an option to just treat it as a warning not an error that prevents the whole reporting being generated. A lot of the time you don't even care about getting coverage info for the class that suffers from this problem, but you do want the rest of the report. And it could be extremely difficult to fix since sometimes the duplicated classes are in third party jars that you unavoidably depend upon. So an option to just ignore the error, or just ignore the problematic class, would be greatly appreciated by eclemma users.

**Comment by marchof** [comment]
@ben-spiller What "tool" are you referring to? EclEmma our code coverage plug-in for Eclipse?

In this case please provide a more detailed description of your setup or maybe even a reproducer. This situation should not happen within Eclipse, as Eclipse does not allow duplicate classes in the same source folder.

**Comment by ben-spiller** [comment]
I'm running the jacoco report tool from ant - apologies I hadn't spotted that the jacoco/eclemma bug database is separate from the jacococ/jacoco database, clearly that's where I should post this, and I'll include a stack trace when I do

Moved to https://github.com/jacoco/jacoco/issues/352
