### ISSUE TITLE
IllegalClassFormatException with Java 8 while instrumentation

### ISSUE THREAD

**Issue by bharath1508** [jacoco/eclemma#109]
I am facing an error while server startup with jacoco 0.7.5 setup & jdk 1.8.51 at instrumenting class. 
The exception - IllegalClassFormatException has been thrown and the root cause is - RunTimeException saying "Class FIle too Large". 
Here, this is generated class through our framework. Hence, i cannot split/divide it into multiple classes. 

To avoid this exception, I have used option - excludes in catalina.bat file. This resulted in no exception but generated jacoco.exec file doesn't contain projects sources related information. It is covering only tomcat server related files inforamtion. Even if i generate report by using this exec, there is 0% coverage.

So can you please assist me to get rid of class size issue. Is there any issue with jacoco against jdk 8. Thanks for help.

**Comment by bharath1508** [comment]
can i have your suggestions regarding above query as i cannot split/divide problem classes into multiple classes, it seems you have closed this as invalid...

**Comment by bharath1508** [comment]
thank you marchof.. I have found your answer in Google groups.. 
Can we have support large class file size in future release..  as i cannot split/divide problem classes into multiple classes becasue those  are generated class through our framework.

**Comment by marchof** [comment]
This is the bug tracker of the EclEmma Eclipse plug-in. For general questions and discussions please use the forum: https://groups.google.com/forum/?fromgroups=#!forum/jacoco
