### ISSUE TITLE
Android Jacoco plugin cannot provide code coverage for Java library modules

### ISSUE THREAD

**Issue by logan203** [jacoco/eclemma#110]
Hello,

It seems that the Android Jacoco Gradle plugin cannot provide code coverage for Java library modules. This can be a problem because the Android UI module often does not contain much code for the code coverage to be comprehensive.

Is there any workaround or any way to fix this?

**Comment by marchof** [comment]
The JaCoCo plug-in for Gradle ist not maintaned by us. AFAIK it is maintained my the Gradle project itself. Please report the problem to the maintainers: https://discuss.gradle.org/
