### ISSUE TITLE
Error while connecting to JaCoCo agent

### ISSUE THREAD

**Issue by balaji-raj** [jacoco/eclemma#114]
I got this error while importing coverage session in jacoco

Error while connecting to JaCoCo agent at address 127.0.0.1 on port 6300 (code 5006).
Connection refused: connect

**Comment by marchof** [comment]
There needs to be a running Java process on localhost with a JaCoCo agent configured (ouput=tcpserver) to import from.

Pleases use our mailing list for general questions: https://groups.google.com/forum/?fromgroups=#!forum/jacoco
