### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by Classe** [jacoco/eclemma#115]
Could you make a new release on the latest master?

**Comment by fape** [comment]
I'd love to use with jacoco 0.7.5+. 
But "The exec file version has been updated and is not compatible with previous versions"...

**Comment by marchof** [comment]
@fape There will be a release this week!

**Comment by marchof** [comment]
@fape Please check the latest trunk build from this update site. If there are no issues there will be a official release soon:

http://download.eclipselab.org/eclemma/trunk/update

**Comment by fape** [comment]
@marchof Thaks. I'm gonna try it out!

**Comment by marchof** [comment]
Done.

**Comment by Classe** [comment]
Thx!
