### ISSUE TITLE
Do you trust these certificates? @Eclipse 4.4.2

### ISSUE THREAD

**Issue by Andrade** [jacoco/eclemma#116]
### Steps to reproduce
1. Help -> Eclipse Marketplace...
2. Search for "eclemma" and click install.
3. Accept license agreement
4. We get a window with the message: "Do you trust these certificates?"

EclEmma version: 2.3.3
Eclipse version: Eclipse IDE for Java Developers 4.4.2
Operating system: Ubuntu 14.04

### Expected behaviour
Such window should not appear.

Could be related to https://stackoverflow.com/a/12604051:
> Short answer: Your certificate is missing an e-mail field in the subject.

### Actual behaviour
![eclemma-cert-trust-2016-03-16](https://cloud.githubusercontent.com/assets/4957940/13813470/b3cfd622-eb79-11e5-924f-8f87b8337adf.png)

**Comment by marchof** [comment]
I cannot reproduce this. Maybe the root certificate is not known to your JDK at all? Can you please check the truststore used by your JDK installation?

**Comment by Andrade** [comment]
I've checked the truststore and found the issue.
 - The root certificate being used is "Thawte Premium Server CA" (Root 2), which is **not** included in the JDK truststore.
 - The truststore does have a root certificate, "Thawte Primary Root CA", but this is the new version (Root 1).

According to https://www.thawte.com/roots/, Root 2 is supposed to be used until mid 2010 and after that time Root 1 takes its place. The page also says vendors should not remove Root 2 until advised, however it is not present in the JDK cacerts hence the warning. (I don't remember adding or removing any root certificates from my installation.)

**Comment by marchof** [comment]
Thanks for checking! What is the exact JRE vendor & version you're using?

**Comment by Andrade** [comment]
$ java -version
    java version "1.7.0_95"
    OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by marchof** [comment]
Seems to be a specific issue with IcedTea JDK. Maybe you report this issue there?

Anyways, thanks for the hint. I will check with Thawte when we need to issue a new certificate and of June.

**Comment by Andrade** [comment]
Reported at http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2884.
