### ISSUE TITLE
Associate to .exec files on MarketPlace

### ISSUE THREAD

**Issue by mickaelistria** [jacoco/eclemma#118]
Starting from Neon M6, Eclipse IDE will feature a mechanism to detect relevant file editor for an unassociated extension. EclEmme should register for the .exec extension. To do that, simply add a tag `fileExtension_exec` to the EclEmma marketplace entry.

**Comment by marchof** [comment]
@mickaelistria Thanks for this hint!

Done: https://marketplace.eclipse.org/content/eclemma-java-code-coverage
