### ISSUE TITLE
No High Resolution Icons available

### ISSUE THREAD

**Issue by LiamHD** [jacoco/eclemma#120]
### Steps to reproduce

EclEmma version: All
Eclipse version: All
Operating system: All
### Expected behaviour

Icons should be sharp an crisp on High Resolution Displays / with operating system level zoom settings
### Actual behaviour

Icons are not sharp and crisp on High Resolution Displays. The eclemma plugins only provide 16x16 pixel GIFs. 
With Eclipse Neon the eclipse platform now supports choosing different icon files dependent on the screen resolution / zoom setting. For details see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=382972#c90. https://git.eclipse.org/r/#/c/73080/ as an example shows how the JDT plugins adopted this capability of the platform.

In the eclipse images repo: http://git.eclipse.org/c/platform/eclipse.platform.images.git icons of the various eclipse projects are stored as SVG. The actual PNGs in the different resolution are generated out of these SVGs.

Shouldn't we also have SVGs of the eclemma icons in the eclipse image repo?

**Comment by marchof** [comment]
EclEmma is (not yet) an Eclipse project, therefore there are no EclEmma cons in the Eclipse repo.

Also I created the Icons long time ago as raster images. We would need a designer to create the SVGs for EclEmma.

**Comment by LiamHD** [comment]
So if you would have the SVGs would you then store them somewhere here in this repo. Some of your icons (e.g. [export.gif](https://github.com/jacoco/eclemma/blob/master/com.mountainminds.eclemma.ui/icons/full/elcl16/export.gif)) already exist as SVG in the eclipse image repo. Can the simply be copied over to this repo?

**Comment by LiamHD** [comment]
Are there concrete plans to become an Eclipse project?

I maybe could redraw the existing icons as SVGs and render PNGs out of them.

**Comment by Godin** [comment]
@LiamHD yes, there are plans, proposal has been published and waits approval - https://projects.eclipse.org/proposals/eclemma

**Comment by Godin** [comment]
I'm closing this ticket - now this is tracked in our new home at Eclipse Foundation: https://bugs.eclipse.org/bugs/show_bug.cgi?id=507724
