### ISSUE TITLE
Use ASM bundle from Eclipse Orbit

### ISSUE THREAD

**Issue by Godin** [jacoco/eclemma#123]

**Comment by marchof** [comment]
@Godin We used to do this but started building our own version as we couldn't get latest ASM version from orbit. Now as we might become a Eclipse project we maybe can trigger Orbit updates faster.

**Comment by Godin** [comment]
@marchof exactly. In fact I created this ticket in response to comments at https://projects.eclipse.org/comment/152#comment-152

**Comment by Godin** [comment]
Should be noted that http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/ contains `5.0.1`, while we already depend on `5.1.0`.

**Comment by Godin** [comment]
Created request for addition of `5.1.0` into Eclipse Orbit - https://bugs.eclipse.org/bugs/show_bug.cgi?id=499638

**Comment by Godin** [comment]
Now this is tracked at https://bugs.eclipse.org/bugs/show_bug.cgi?id=500356
