### ISSUE TITLE
Opening the tree node for a several-hundred method class is slow

### ISSUE THREAD

**Issue by akarnokd** [jacoco/eclemma#129]
### Steps to reproduce

Easiest is to check out RxJava branch 2.x, run the coverage and open the node for `io.reactivex.Observable` in the Coverage view. It takes tens of seconds on my i7 4770 and almost a minute on my Celeron 1005 laptop. I have my table ordered by the percentage ascending. The class has several hundred methods in it.

EclEmma version:  2.3.3.201602231923  
Eclipse version: 4.6.0 20160613-1800
Operating system: Windows 7 x64, Java 8u102
### Expected behaviour

The tree node opens up within 2-6 seconds or less.

**Comment by marchof** [comment]
Coverage for method elements is identified lazily when the a method of a type ist requested for the first time. In this case coverage nodes for all methods are loaded and cached:

https://github.com/jacoco/eclemma/blob/master/com.mountainminds.eclemma.core/src/com/mountainminds/eclemma/internal/core/analysis/JavaModelCoverage.java

Maybe there is a problem with caching or the performance characteristic of MethodLocator for very large classes.

Can you please provide a example class which reproduces the problem? I think method signatures should be enough (no method bodies required).

**Comment by akarnokd** [comment]
[Here](https://gist.github.com/akarnokd/837e18beec6f4c2bbfdba87bde9ab757) is a class with many trivial methods but I have no problems opening that. [This](https://raw.githubusercontent.com/ReactiveX/RxJava/2.x/src/main/java/io/reactivex/Observable.java) is the file that definitely exhibits this problem.

I have flight-recorded when I open its class node:

![image](https://cloud.githubusercontent.com/assets/1269832/18049983/09270bb4-6dec-11e6-9c65-d55ec43ffe85.png)

![image](https://cloud.githubusercontent.com/assets/1269832/18050002/2c2b384c-6dec-11e6-8113-a0fc2b6c116c.png)

Looks like it might nothing to do with EclEmma as Eclipse is otherwise particularly slow on that class; whenever I update it it takes half a minute up to 5 minutes to compile (javac finishes with the whole project under 10 seconds).

Unless you can think of a way to bypass the slow method in Eclipse, this issue can be closed.

**Comment by marchof** [comment]
@akarnokd Thank's for the detailed analysis! How long does it take to open the "bad class" in another Eclipse tree UI, like Project Explorer?

**Comment by akarnokd** [comment]
It opens practically immediately and I had no problems with the outline view of it either. Only compilation and opening the coverage node is slow.

**Comment by marchof** [comment]
Ok, looking at your performance analysis probably reveals the problem: To map overloaded methods to coverage nodes EclEmma has to resolve the type parameters, which triggers compilation:

![image](https://cloud.githubusercontent.com/assets/1936262/18051624/f8be6286-6df5-11e6-8406-2a8ddcf71a2c.png)

I don't thinks there is much we can do about this.

**Comment by akarnokd** [comment]
So does EclEmma call compile for each overloaded method or just once per class?

**Comment by marchof** [comment]
Good question: EclEmma calls resolveType for every parameter of methods which cannot be distinguished by their name and parameter count. But I would expect JDT to compile the underlying file just once.

https://github.com/jacoco/eclemma/blob/master/com.mountainminds.eclemma.core/src/com/mountainminds/eclemma/internal/core/analysis/MethodLocator.java

**Comment by marchof** [comment]
@akarnokd In the meantime I found some tine to investigate further. This standalone example kills EclEmma exactly the way you describe it. The example contains 1000 methods named "m", each with 10 parameters to resolve:

https://gist.github.com/marchof/91e16b186e38d9f854f1ff1dc24c03a7

I definitely think we have an caching issue here with type resolving. I'll open a bug at our new home at eclipse.org.

**Comment by marchof** [comment]
We will try to resolve this issue at our new home: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512756
