### ISSUE TITLE
Test Coverage fails when the number of test cases exceeds 15

### ISSUE THREAD

**Issue by ghaimehak** [jacoco/eclemma#135]
Is there any maximum limit for the number of test cases to be executed at once to find out the test case code coverage ? Please look into it and reply back as soon as possible.

### Steps to reproduce
Try running a JUnit file with more than 15 test cases. 
EclEmma version: Latest
Eclipse version: Luna
Operating system: Windows 7

### Expected behaviour
Should show the coverage for the entire file.

### Actual behaviour
Once it exceeds 15 the coverage throws the following error. 'com.mountainminds.eclemma.internal.core.launching.AgentServer' has encountered a problem.

**Comment by marchof** [comment]
We have testsuites > 100,000 test cases.

To investigate this please provide

- full error message and stack trace from the Eclipse log
- the a specific reproducer

**Comment by ghaimehak** [comment]
Below is the stack trace:

![screenshot3](https://cloud.githubusercontent.com/assets/25606937/22731024/4245310c-ee0f-11e6-8036-76e1f6cb9c97.PNG)


Screenshots of error:

![screenshot1](https://cloud.githubusercontent.com/assets/25606937/22731039/4973e5f4-ee0f-11e6-9d08-19dde21e235c.PNG)

![screenshot2](https://cloud.githubusercontent.com/assets/25606937/22731050/52906fcc-ee0f-11e6-9623-ec273e363f94.PNG)


It terminates after reaching the 16th test case of a specific file and even while running the code coverage for all the files in a package.

The code is confidential. 

Any help based on the above information would be appreciated.

**Comment by Godin** [comment]
@ghaimehak if it fails when reaching always the same 16th test, then
- what happens if you run this test alone?
- what happens if you remove this test and run all remaining?

**Comment by ghaimehak** [comment]
It doesn't fail at the same test case. It fails after execution of any 15 test cases. 

Also, I've tried running all the test cases individually and they work fine. All individual files with less than 16 test cases also run fine.

**Comment by Godin** [comment]
@ghaimehak in this case another wild guess: check that JVM does not reach OutOfMemoryError when executing those tests with coverage.

**Comment by Godin** [comment]
Here is what I've tried on Mac and Linux in Eclipse IDE for Java Developers (Version: Neon.2 Release (4.6.2) Build id: 20161208-0600) with EclEmma 2.3.3.201602231923 and JDK 8u121 :

```
import org.junit.Test;

public class Example {

	private static void crash() {
		sun.misc.Unsafe unsafe;
		try {
			java.lang.reflect.Field f = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
			f.setAccessible(true);
			unsafe = (sun.misc.Unsafe) f.get(null);
		} catch (IllegalArgumentException | IllegalAccessException | NoSuchFieldException | SecurityException e) {
			throw new RuntimeException(e);
		}
		unsafe.putAddress(0, 0);
	}

	private static int[] consumeMemory() {
		int iteratorValue = 20;
		for (int outerIterator = 1; outerIterator < 12; outerIterator++) {
			iteratorValue = iteratorValue * 5;
		}
		return new int[iteratorValue];
	}

	@Test
	public void testTerminateInEclipse() throws InterruptedException {
		Thread.sleep(Long.MAX_VALUE);
	}
	
	@Test
	public void testConsumeMemory() {
		consumeMemory();
	}
	
	@Test
	public void testCrash() {
		crash();
	}
	
	@Test
	public void testConsumeMemoryDuringShutdown() {
		Runtime.getRuntime().addShutdownHook(new Thread() {
			@Override
			public void run() {
				consumeMemory();
			}
		});
	}
	
	@Test
	public void testCrashDuringShutdown() {
		Runtime.getRuntime().addShutdownHook(new Thread() {
			@Override
			public void run() {
				crash();
			}
		});
	}

}
```

And the only case when popup "No Coverage Data" appears - is `testCrash`, but console clearly shows JVM crash.

And none leads to "Socket Exception: Connection reset", so no idea how to reproduce your case without example or additional details about tests from you. The best way will be - is to create example that won't be confidential.

Also in any case - check console output.

**Comment by Godin** [comment]
@ghaimehak since you closed this issue, does it mean that you found cause? if so, would be nice to share it for further readers of this thread. Thanks.
