### ISSUE TITLE
Wrong return type in function error

### ISSUE THREAD

**Issue by xploreraj** [jacoco/eclemma#136]
I tried running FTs against a deployed version of the app in stage, the source code of which is present in eclipse along with FTs.
Also I tried this with unit tests, but same error.

### Steps to reproduce
Coverage a test as -> Test NG

Specs:
1. EclEmma - 2.3.3 (latest from eclipse marketplace)
2. Eclipse -   Eclipse IDE for Java EE Developers        4.5.1.20150917-1200        epp.package.jee (this is a customized eclipse used in our company as a standard and projects are dependent on the custom frameworks included)
3. MacOS

### Actual behaviour
An internal error occurred during: "Analyzing coverage session com.mycomp.rest.raj.MessageTest.testMethod (Feb 27, 2017 10:04:32 AM)". (class: org/jacoco/core/internal/flow/ClassProbesAdapter, method: visitMethod signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Lja‌​va/lang/String;)Lorg‌​/objectweb/asm/Metho‌​dVisitor;) Wrong return type in function

**Comment by marchof** [comment]
Same question has also been posted on mailing list:
https://groups.google.com/d/msg/jacoco/NjixkV5rtlw/TQYv0Q5JCwAJ

**Comment by marchof** [comment]
@xploreraj To investigate this can you please provide the
following information:

1) Full stack trace from the Eclipse log file (from .log file from
<workspace>/.metadata)
2) Complete plugin version list (from About --> Installation Details -->
Configuration --> Sections "Features" and "Plug-in Registry")

**Comment by xploreraj** [comment]
How do I send it to you privately? This has company info.

**Comment by xploreraj** [comment]
Sent you an email.

**Comment by marchof** [comment]
@xploreraj Thanks for providing the logfiles as direct message!

You're using a quite old version EclEmma 2.3.0 of EclEmma which actually had an issue (#83) with ASM version conflicts.

Please [install the latest EclEmma release](http://www.eclemma.org/installation.html).

**Comment by marchof** [comment]
Duplicate #83.

**Comment by xploreraj** [comment]
Hi Marc, really sorry. I checked the #83 issue earlier but looked at marketplace and it showed me 2.3.3, I did not notice the Update button below in hurry. Now I am able to see colors, and exploring it for the first time. Thank you very much. I am exploring it for FTs that connect to stage, but code is in local workspace too. Let me see. Once again, thanks a ton for quick resolution.
