### ISSUE TITLE
Update site is down or moved?

### ISSUE THREAD

**Issue by iloveeclipse** [jacoco/eclemma#137]
Tried to install eclemma from Oxygen M7, no luck:
No repository found at http://update.eclemma.org/.

Is the update site moved? Where is the new one of the org.eclipse.eclemma project?

**Comment by iloveeclipse** [comment]
Just found out that there is a new update site for master: http://download.eclipse.org/eclemma/updates-master/

**Comment by marchof** [comment]
Hi @iloveeclipse thanks for the hint! The update site is supposed to work.

I changed permissions last night and obviously made a mistake. Update site should be back online. Sorry for the inconvenience.
