### ISSUE TITLE
EclEmma disapeared from Eclipse

### ISSUE THREAD

**Issue by nrivard63** [jacoco/eclemma#138]
### Steps to reproduce

EclEmma version: 2.3.3
Eclipse version: 4.6.2
Operating system: Windows 7

### Expected behaviour
EclEmma should be visible in the toolbar and menus (Coverage as...)

### Actual behaviour
I installed successfully last week and it worked well until today after I rebooted the PC. Now it is nowhere in the menu or toolbar, however, Eclipse Marketplace tells me it is still installed. I tried to uninstall and reinstall, with same result.

**Comment by marchof** [comment]
Please provide the your installation details:

    About Dialog --> Installation Details --> Tab Configuration

Thx.

**Comment by Godin** [comment]
@nrivard63 any updates on this? will close otherwise.

**Comment by Godin** [comment]
I'm closing this ticket in absence of requested information.

**Comment by nrivard63** [comment]
That's fine. We figured out EclEmma requires the Eclipse update to fix the problem.

**Comment by Godin** [comment]
@nrivard63 Could you please elaborate a bit more about the required update, so that this information might be used by other users that might face same issue?

**Comment by nrivard63** [comment]
Sure. At the office we are using Eclipse Neon.2. EclEmma was working fine on my station until we had a Windows update which made EclEmma unavailable in my Eclipse installation. The Eclipse Marketplace tool said it was still installed, however I lost the Coverage menu. The technical support guy told me he had to install the Eclipse update to fix this. He did and EclEmma was back. Tomorrow I will l ask him more detail about the update he installed. Thanks
