### ISSUE TITLE
Static variable in a class is shown uncovered in the code coverage

### ISSUE THREAD

**Issue by sharmahimanshu2** [jacoco/eclemma#139]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.eclemma.org/faq.html

### Steps to reproduce
Create a class with static variable and static method , call static variable and check if the static variable are covered in the code coverage

EclEmma version: 2.2.1
Eclipse version: 4.3.1
Operating system: Windows 7

### Expected behaviour
Code coverage must cover static variable when called

### Actual behaviour
Code coverage is not covering the static variable evenif called

**Comment by marchof** [comment]
@sharmahimanshu2 Static variables itself are not executable code. Can you please show a specific example and explain what you expect to see?

**Comment by sharmahimanshu2** [comment]
Suppose we have a code in which static member variable are created and called in the same class in different methods and is uncovered at one location

```
class Foo{

	static Foo1 Foo1var = null; // this line will be shown uncovered by JaCoCo plugin
		
	void methodA() // Covered : this method is called
	{
		Foo1var = new Foo1();
	}

	void methodB() // Covered : this method is called
	{
		Foo1var.setVal(23);
	}
	
	void methodC() // Uncovered : this method is not called
	{
		int result = Foo1var.getVal();
	}
}


class Foo1{

	static int varInt;
	
	
	public int getVal()
	{
		return varInt;
	}

	public int setVal(int val)
	{
		varInt = val;
	}
}
```

will line `static Foo1 Foo1var = null; ` be covered or not?

Currently, it is shown uncovered.

Please suggest

**Comment by Godin** [comment]
@sharmahimanshu2 In general there is no magic:
If compiler generates code associated with some line and you execute this code, then line will be marked as covered.
If compiler generates code associated with some line and you do not execute this code, then line will be marked as uncovered.
If compiler doesn't generate code for some line, then it will be marked as empty.

For your example using the same environment ( Eclipse 4.3 Kepler , EclEmma 2.2.1 ):

![about_eclipse_features_and_about_eclipse_and_java_-_example_src_example_example_java_-_eclipse_-__private_tmp_eclipse_workspace](https://user-images.githubusercontent.com/138671/27829320-585878e4-60c1-11e7-9fe6-32265ba53521.png)

BTW version 2.2.1 of EclEmma is 4 years old, please upgrade and use latest. Version of Eclipse also quite old - please consider upgrading.
