### ISSUE TITLE
Mismatch Code Coverage Percentage

### ISSUE THREAD

**Issue by sunilnshetty** [jacoco/eclemma#140]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.eclemma.org/faq.html

Copper Project

![image](https://user-images.githubusercontent.com/7489829/28963761-eaa64efa-7927-11e7-8671-f09aacd829c2.png)

![image](https://user-images.githubusercontent.com/7489829/28963778-02177eb0-7928-11e7-8e24-f9afc56f02d3.png)

Common Project

![image](https://user-images.githubusercontent.com/7489829/28963861-46ea300a-7928-11e7-8d22-4d05edf996a4.png)

![image](https://user-images.githubusercontent.com/7489829/28963888-5e896db6-7928-11e7-8288-d73d1eb3740b.png)

### Steps to reproduce

There is test class "TestCopperPathManagerMove.java" containing test cases. It uses class rules to prepare data. Something like this

@ClassRule
    public static RuleChain classchain = RuleChain.outerRule(classtransactionResource)
            .around(classRegions).around(classFdsRes).around(classLocales).around(classIsams)
            .around(classLocations).around(chorusSrPhysicalDeviceResource)
            .around(multiChorusSrPhysicalPortResource).around(classCopperPathResource);

class rule resources like classtransactionResource, classRegions etc are in Common Project.

When I generate code coverage report by running TestCopperPathManagerMove.java in Common Project. Code Coverage Percentage is 84.6%.

When I generate code coverage report by running TestCopperPathManagerMove.java in Copper Project, Code Coverage Percentage is 95.8%. There is dependency from Common project to Copper project.

How to solve this issue?

EclEmma version: Latest
Eclipse version: Luna Service Release 2 (4.4.2)
Operating system: Windows 7

### Expected behaviour

Code Coverage Percentage is 95.8%.

### Actual behaviour

Code Coverage Percentage is 84.6%.

**Comment by marchof** [comment]
@sunilnshetty What looks strange here is that 10 missing branches are reported in line 125 in the missing case while in the green case no branches are shown at all in 125 (as expected, no green diamond in the left ruler). Something strange here in this setup 

Can you please provide the *.java and *.class files of TestCooperPathManagerMove from the setup where you see the missing branches?

**Comment by sunilnshetty** [comment]
[eclemmaIssue.zip](https://github.com/jacoco/eclemma/files/1230699/eclemmaIssue.zip)

PFA Both *.java and *.class file.

**Comment by marchof** [comment]
@sunilnshetty Thanks, this shows the issue. I decompiled (`javap -c`) the class file [here](https://gist.github.com/marchof/c3132b8a53364efa57533157b7630fd1).

As you can see there is lots of instrumentation code in this class. In the static initializer (which originally ends at line 133) lots of additional AspectJ code added.:

       235: goto          263
       238: astore_0
       239: aload_0
       240: instanceof    #714                // class java/lang/ExceptionInInitializerError
       243: ifeq          251
       246: aload_0
       247: checkcast     #714                // class java/lang/ExceptionInInitializerError
       250: athrow
       251: nop
       252: invokestatic  #718                // Method ajc$com_nokia_lni_aspect_trace_TraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/TraceAspect;
       255: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       258: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       261: aload_0
       262: athrow
       263: invokestatic  #718                // Method ajc$com_nokia_lni_aspect_trace_TraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/TraceAspect;
       266: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       269: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       272: goto          300
       275: astore_1
       276: aload_1
       277: instanceof    #714                // class java/lang/ExceptionInInitializerError
       280: ifeq          288
       283: aload_1
       284: checkcast     #714                // class java/lang/ExceptionInInitializerError
       287: athrow
       288: nop
       289: invokestatic  #730                // Method ajc$com_nokia_lni_aspect_trace_VoidTraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/VoidTraceAspect;
       292: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       295: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       298: aload_1
       299: athrow
       300: invokestatic  #730                // Method ajc$com_nokia_lni_aspect_trace_VoidTraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/VoidTraceAspect;
       303: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       306: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       309: goto          337
       312: astore_2
       313: aload_2
       314: instanceof    #714                // class java/lang/ExceptionInInitializerError
       317: ifeq          325
       320: aload_2
       321: checkcast     #714                // class java/lang/ExceptionInInitializerError
       324: athrow
       325: nop
       326: invokestatic  #734                // Method ajc$com_nokia_lni_aspect_trace_SimpleSetterAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/SimpleSetterAspect;
       329: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       332: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       335: aload_2
       336: athrow
       337: invokestatic  #734                // Method ajc$com_nokia_lni_aspect_trace_SimpleSetterAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/SimpleSetterAspect;
       340: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       343: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       346: goto          374
       349: astore_3
       350: aload_3
       351: instanceof    #714                // class java/lang/ExceptionInInitializerError
       354: ifeq          362
       357: aload_3
       358: checkcast     #714                // class java/lang/ExceptionInInitializerError
       361: athrow
       362: nop
       363: invokestatic  #738                // Method ajc$com_nokia_lni_aspect_trace_ConstructorTraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/ConstructorTraceAspect;
       366: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       369: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       372: aload_3
       373: athrow
       374: invokestatic  #738                // Method ajc$com_nokia_lni_aspect_trace_ConstructorTraceAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/ConstructorTraceAspect;
       377: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       380: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       383: goto          415
       386: astore        4
       388: aload         4
       390: instanceof    #714                // class java/lang/ExceptionInInitializerError
       393: ifeq          402
       396: aload         4
       398: checkcast     #714                // class java/lang/ExceptionInInitializerError
       401: athrow
       402: nop
       403: invokestatic  #742                // Method ajc$com_nokia_lni_aspect_trace_SimpleGetterAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/SimpleGetterAspect;
       406: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       409: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V
       412: aload         4
       414: athrow
       415: invokestatic  #742                // Method ajc$com_nokia_lni_aspect_trace_SimpleGetterAspect$localAspectOf:()Lcom/nokia/lni/aspect/trace/SimpleGetterAspect;
       418: getstatic     #720                // Field ajc$tjp_0:Lorg/aspectj/lang/JoinPoint$StaticPart;
       421: invokevirtual #726                // Method com/nokia/lni/aspect/trace/AbstractTraceAspect.initLogger:(Lorg/aspectj/lang/JoinPoint$StaticPart;)V

JaCoCo works directly on class files and reports exactly what it sees there. For a proper coverage report I recommend running your code on uninstrumented code.

**Comment by sunilnshetty** [comment]
Thanks.

How to generate code coverage report by uninstrumented method using eclemma plugin in eclipse?

**Comment by marchof** [comment]
@sunilnshetty Please check with the vendor of the instrumentation tool you're using how to disable it.
