### ISSUE TITLE
no coverage data 

### ISSUE THREAD

**Issue by dimense** [jacoco/eclemma#141]
This is a issue tracker. Please use our mailing list for general questions: 
https://groups.google.com/forum/?fromgroups=#!forum/jacoco

Also check FAQ before opening an issue: http://www.eclemma.org/faq.html

### Steps to reproduce
1.start process script:
JAVA_OPTS=" -javaagent:/opt/huawei/jacoco/lib/jacocoagent.jar:dumponexit=true,includes=com.*,output=file,destfile=/opt/huawei/jacoco/data/work.exec -Xms512m -Xmx1024m"
nohup java $JAVA_OPTS -cp ../lib/*:../conf com.huawei.olc.WorkerBootstrap >> $WORK_DIR/logs/run.log 2>&1 &
2.start process
3.excute some case,then check coverage data
host-10-24-0-20:/opt/huawei/worker/bin # ll /opt/huawei/jacoco/data/
total 0
-rw-r--r-- 1 root root 0 Aug  8 10:43 work.exec

so please analys the problem ,ths

EclEmma version:0.7.9
Eclipse version:
Operating system:suse 

byw:windows is ok,unbantu is ok,suse is not ok.

**Comment by Godin** [comment]
@dimense First of all - this is old repository of EclEmma Eclipse plugin, while you're talking about JaCoCo library, which is hosted in another repository.

In your setup (`output=file`) JaCoCo creates empty exec-file to ensure that output location (`destfile`) is writable, and writes all the data at the JVM termination (`dumponexit=true`). So while JVM is not terminated and dump of data is not requested explicitly, it is normal that file stays empty.
