### ISSUE TITLE
PowerMock disables EclEmma code coverage

### ISSUE THREAD

**Issue by liptga** [jacoco/eclemma#15]
Original report can be seen here: http://code.google.com/p/powermock/issues/detail?id=402

Powermock guys asked us to report here as well.

What steps will reproduce the problem?
1.Create a powermock test with Mockito, the test class is decorated with @RunWith and @PrepareForTest annotation.
2.Run the Test with "coverage as".

What is the expected output? What do you see instead?
Expected: EclEmma shows correct code coverage report.
Instead: EclEmma shows zero code coverage on target class.

What version of the product are you using? On what operating system?
1. Eclipse is 3.7. 
2. EclEmma Plugin: 2.1.4. 
3. PowerMock: powermock-mockito-1.4.12-full.jar.
4. OS: Windows XP sp2. 
5. JDK: 1.6.

Please provide any additional information below.
N/A.

**Comment by ashwinganeshk** [comment]
I know its pretty late but, [this](http://stackoverflow.com/a/27769038/653211) pretty much did the trick. I used sonar for analysis.

**Comment by ProTrent** [comment]
New link to Agent: https://github.com/jayway/powermock/wiki/PowerMockAgent
