### ISSUE TITLE
EclEmma Eclipse plugin : wrong code coverage detection

### ISSUE THREAD

**Issue by BBE78** [jacoco/eclemma#65]
EclEmma Eclipse plugin provides wrong code coverage detection. Attached you will find a screen capture that will explain the issue

JUnit Test code coverage is displayed with 76,5% but this is false : 100% shall be displayed
![eclemma](https://f.cloud.github.com/assets/5666567/1317255/9f73732c-32a4-11e3-9c1c-ce29136de859.png)

**Comment by julesbond007** [comment]
Hi there,

I was wondering about this as well...in the subsequent probes, couldn't we check if the unit test has the expected exception?  Then consider the lines executed so far as covered?

Thanks,

Jay
