### ISSUE TITLE
Exclude some files from the coverage total

### ISSUE THREAD

**Issue by denevell** [jacoco/eclemma#70]
Let's say I have the files below in the same source tree

com.example.entitites.SimplePojo
com.example.something.SomethingTests

I don't want eclemma to include those files in what needs to be covered tested.

I have seen the 'excludes' preference in Eclipse, but placing classes in such do not remove them from the coverage total: in the coverage window they still appear, as 0% and their code still highlighted red (even if they were partly green before.)

Is it possible to exclude classes from what needs to be covered by tests?

**Comment by rtack** [comment]
Shouldn't this website be updated then? http://www.eclemma.org/userdoc/preferences.html

It says
Excludes: A list of class names that should be excluded from execution analysis. The list entries are separated by a colon (:) and may use wildcard characters (* and ?). (Default: empty)

**Comment by marchof** [comment]
If you read on the page says:

> Warning: Use these options with caution! Invalid entries might break the code coverage launcher. Also do not use these options to define the scope of your analysis. **Excluded classes will still show as not covered.**

**Comment by monism** [comment]
Hi All,

I am trying  to exclude a class that i  know have coverage in it. Once i put that to the excludes preference, on a new coverage run they'll still be there in the coverage window, but they'll come up as 0% and will all be in red.

Is there a solution which to solve this , i need to exclude a class and not be showing in report at all

**Comment by marchof** [comment]
@monism Check my last comment I posted here. This is how the option is designed. EclEmma does not support exclusion of individual classes from the report.

**Comment by monism** [comment]
@marchof  so there is no way now. i can exclude the classes as i have jacoco.exec and html file report, can you just help me in solving this

**Comment by marchof** [comment]
@monism Please do not post to closed issues. Our mailing list is a great place to ask general questions: https://groups.google.com/d/forum/jacoco
