### ISSUE TITLE
Coverage As contributed to every pop-up menu

### ISSUE THREAD

**Issue by alblue** [jacoco/eclemma#87]
The "Coverage As" menu is added to any pop-up view, even for things that don't make sense. For example, creating a plug-in using the sample view template results in a 'coverage as' on the selected elements:

![screen shot 2014-06-23 at 13 30 00](https://cloud.githubusercontent.com/assets/76791/3357500/266f9b26-fad2-11e3-94c8-0a51e323d833.png)

This is because the object contribution for the pop-up is java.lang.Object, which means it will select any object to contribute its resources to. Instead, if this were IResource, it would only support elements who were capable of being cast to an IResource (e.g. files, projects).

Steps to reproduce:
- Install EclEmma 2.3.1
- File -> New -> Plug-in project
- Next -> Next
- Create a plug-in using the "Plug-in with a view" template
- Accept defaults and click Finish
- Run an Eclipse application
- Window -> Show View -> Other -> Sample Category -> Sample View
- Right-click on Three
- The 'Coverage as' menu is seen

**Comment by Godin** [comment]
@marchof do you see any problem to accept https://github.com/alblue/eclemma/commit/16bc83503c46faac7304cbb02501a7fb2c73fd38 as a fix ?

**Comment by marchof** [comment]
@Godin No, this might disable launching at places where it is possible today and will not fix the problem for other places.

The only correct is plug-in activation. We need to do some performance measurements what the cost for activation EclEmma actually is.

**Comment by Godin** [comment]
I'm closing this ticket - progress of resolution is tracked in our new home at Eclipse Foundation: https://bugs.eclipse.org/bugs/show_bug.cgi?id=501545

**Comment by marchof** [comment]
@Godin FYI: Created a label for such issues.

**Comment by Godin** [comment]
@marchof I was adding them to "Eclipse Foundation" milestone :)

**Comment by marchof** [comment]
@Godin Makes sense! I delete the label again.

**Comment by Godin** [comment]
@marchof btw, do you receive notifications from bugzilla on mention (like for this ticket)?

**Comment by marchof** [comment]
@Godin Unfortunatelly not. Any idea how I can turn this on in Bugzilla preferences?

**Comment by Godin** [comment]
@marchof I don't know, actually I even don't know if this is a right way to summon someone.

@mickaelistria was suggesting to 

> Go to https://bugs.eclipse.org/bugs/userprefs.cgi?tab=email , and add to the watch-list "eclemma-inbox@eclipse.org". This is the symbolic URL that will be used as default assignee when bugs are reported against EclEmma. By adding it to the watchlist, you'll receive the most useful notifications when a bug is created.

I'm not sure that it works for already assigned bugs. Alternatively I could add you to CC list each time I wanna summon you :)

@mickaelistria any advice? or maybe there is some guide about how to use Eclipse bugzilla?

**Comment by mickaelistria** [comment]
> I'm not sure that it works for already assigned bugs.

On this same page, one can decide which kinds of notification to receive. There might be a way to follow all bugs for a project, even assigned ones.

> Alternatively I could add you to CC list each time I wanna summon you :)

This is the usual approach with bugzilla, to add people as CC.

> maybe there is some guide about how to use Eclipse bugzilla?

AFAIK, there is no guide specific to Eclipse.org ones, but general bugzilla docs apply.
